name: Deploy to Fly.io

on:
  push:
    branches:
      - master

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check for backend changes
        id: check-backend
        run: |
          if git diff --name-only HEAD~1 | grep -q "^backend/"; then
            echo "backend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "backend_changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Deploy Backend
        if: steps.check-backend.outputs.backend_changed == 'true'
        run: |
          cd backend
          flyctl deploy -a backend-quiet-shadow-370
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Check for frontend changes
        id: check-frontend
        run: |
          if git diff --name-only HEAD~1 | grep -E "^(src/|nginx\.conf|package\.json|vite\.config\.js)"; then
            echo "frontend_changed=true" >> $GITHUB_OUTPUT
          else
            echo "frontend_changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Deploy Frontend
        if: steps.check-frontend.outputs.frontend_changed == 'true'
        uses: superfly/flyctl-actions@master
        with:
          args: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP: workalert 