name: Fly Deploy All

on:
  push:
    branches:
      - master

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'backend/') || contains(github.event.head_commit.added, 'backend/')
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy Backend
        uses: superfly/flyctl-actions@master
        with:
          args: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP: backend-quiet-shadow-370
        working-directory: ./backend

  deploy-frontend:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.modified, 'src/') || contains(github.event.head_commit.added, 'src/') || contains(github.event.head_commit.modified, 'nginx.conf') || contains(github.event.head_commit.added, 'nginx.conf')
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy Frontend
        uses: superfly/flyctl-actions@master
        with:
          args: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP: workalert 