# This workflow is disabled - use fly-deploy-all.yml instead
name: Fly Deploy Backend (DISABLED)

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: This workflow is disabled
        run: echo "Use fly-deploy-all.yml instead" 