name: Fly Deploy Backend

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy Backend
        uses: superfly/flyctl-actions@master
        with:
          args: deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP: backend-quiet-shadow-370
        working-directory: ./backend 