# This workflow is disabled - use fly-deploy-all.yml instead
name: Fly Deploy Frontend (DISABLED)

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'backend/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: This workflow is disabled
        run: echo "Use fly-deploy-all.yml instead"
